### ISSUE TITLE
Support client certificate login

### ISSUE THREAD

**Issue by calebkiage** [microsoftgraph/msgraph-cli#147]
Support the [client certificate credential](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.clientcertificatecredential?view=azure-dotnet) login

**Comment by darrelmiller** [comment]
After a series of conversations with people on this topic, I would like to propose that we change one of our security requirements for both CLI and PowerShell.

Currently we do not allow the use of clientSecret in order to perform a "Client Credentials" flow.  The justification for this limitation is that we don't want people writing scripts to accidentally commit secrets into source control.

In PowerShell you can perform ClientCredentials login using a certificate that was pulled from the certificate store, or an instance of a Certificate Object that a script created.  There is no equivalent to this second method that works for the CLI environment.  In order to use a certificate that has been stored on disk it is necessary to have a password available.  Having a password for a certificate brings us back to the risk of the secret being stored in a file that is committed to source control, but worse.

clientSecrets generated by AAD App Registration have a specific format that can be detected by source control platforms like GitHub and Azure DevOps.  Detecting a saved certificate password reliably is much harder.

This leads me to the conclusion that it is actually safer to allow clientSecrets be used for Client Credentials than using a certificate that is not in the certificate store.

My proposal is that for the CLI we either read certificates from the cert store, or we allow the use of clientSecret but we don't try and read a certificate from disk.  We should also plan to add clientSecret support to PowerShell for consistency.

@ddyett @calebkiage @baywet @maisarissi @CarolKigoonya @peombwa

**Comment by calebkiage** [comment]
Hey, thanks for your input @darrelmiller. I have a question about the secret detection. Do we leave this up to the user to create a secret detection tool and add it to their CI or should we make a tool that they can add to their CI that will detect the secrets?

**Comment by baywet** [comment]
It's automatic on some repos hosting platforms and can also be implemented through CI on other platforms (like CredScan)
https://docs.github.com/en/code-security/secret-scanning/secret-scanning-patterns#supported-secrets-for-partner-patterns

**Comment by maisarissi** [comment]
As part of PS SDK v2 we are also [adding support for managed service identity (MSI)](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/721).

**Comment by baywet** [comment]
@calebkiage could you create additional issues for managed identity, environment, and client secret login please so we don't loose tracks of that work when this one gets closed?

**Comment by calebkiage** [comment]
Hey @baywet, sure.
