### ISSUE TITLE
Analysis of failing Raptor Tests

### ISSUE THREAD

**Issue by ddyett** [microsoftgraph/msgraph-cli#263]
- [x] Do analysis of failing tests
- [x] Increase # of tests for the CLI

**Comment by timayabi2020** [comment]
1. Analysis of execution tests that were failing is complete. It was established that, of the 429 failing tests, 420 was due to missing test data while 9 was due to non-related data issues. i.e. Snippets that can't be executed by CLI.  See logged issue here https://github.com/microsoftgraph/msgraph-cli/issues/309.
2. Number of CLI snippets (1214) available for testing is slightly higher than Csharp  v1.0 snippets (1169). This is because the percentage of snippet generation for CLI (91.62%) is slightly higher than Csharp (90.96%).
